### PR TITLE
Multicomponent flow with variable fluid properties (feature_multicomp) 

### PR DESCRIPTION
**Pull request by mheimgartner**
It goes with su2code/SU2/pull/1332

### CODE REVIEW

**Comment by TobiKattmann** [comment]
please make this merge into feature_flamelet and watch out for changes in #70 . Best you go there and click the subscribe bell (and dont forget to like and comment...)

**Comment by pcarruscag** [comment]
Apologies for the mess but master and develop had diverged and I had to rebase develop to fix it.
It may be easier to cherrypick your changes onto the new develop to fix the conflicts.

**Comment by TobiKattmann** [comment]
Other than #70, there were added Testcases that go with the code PR. So @bigfooted @Cristopher-Morales , in case someone continues the multi-component stuff it might be worthwhile to set up a new Testcases branch and either cherry-pick the commits as pedro suggests (but hand copying and new commits works as well ;)

**Comment by bigfooted** [comment]
Thanks! This week we will be ready to run these testcases with the devel+multicomp merge, so we'll tackle this soon I hope.

**Comment by bigfooted** [comment]
Since we have many new regression tests for species transport implemented by @Cristopher-Morales, I don't think we will need this testcase anymore. I will close it.

**Pull request closed without merging**
