### PR TITLE
Add mesh file and TargetEA.dat for PR 1329

### PR DESCRIPTION
**Pull request by snow54**

### CODE REVIEW

**Comment by pcarruscag** [comment]
Thank you for adding a test. Do you have a coarser mesh? Our tests already take a little to run ~20min, do you know more or less how long it would take to run 20 iterations of this on 2 cores?

**Comment by snow54** [comment]
> Thank you for adding a test. Do you have a coarser mesh? Our tests already take a little to run ~20min, do you know more or less how long it would take to run 20 iterations of this on 2 cores?

I can try to make coarser mesh. Direct run takes ~1.5sec for one iteration on my 4-core PC, so it probably takes around 1min on 2 cores. Adjoint takes about 3 times of direct, so it probably takes around 3min.

**Comment by pcarruscag** [comment]
Ok. Please try to make a coarser mesh, the largest 3D mesh we have in the regressions is 40k and it is structured.

**Comment by snow54** [comment]
I have replaced the mesh with one with 22k nodes.

**Pull request merged**
