### PR TITLE
V&V case composition-dependent model (Sandia Jet)

### PR DESCRIPTION
**Pull request by sjhbtue**
This PR contains the required file for the regression test of the sandia jet V&V case in the TestCases repository.

### CODE REVIEW

**Comment by pcarruscag** [comment]
Didn't you add meshes to the V&V repo already?

**Comment by sjhbtue** [comment]
Solution file has been added.

**Comment by sjhbtue** [comment]
@pcarruscag Is something else needed for this PR? Thanks in advance!

**Comment by pcarruscag** [comment]
Should be enough If the regressions run ok, thanks.

**Pull request merged**
